#!/usr/bin/env bash

## Sets up the java enviroment to run a command from RDF Delta.

# Location of the delta-server.jar, which also contains the commands.
DELTA_HOME="${DELTA_HOME:-$PWD}"
CP=''
if [[ -e "$DELTA_HOME/delta-patch-server.jar" ]] ; then
    CP="$DELTA_HOME/delta-patch-server.jar"
elif [[ -e "$DELTA_HOME/delta-server.jar" ]] ; then
    CP="$DELTA_HOME/delta-server.jar" 
else
    echo "Can't find the jar containing the RDF Delta cmds (delta-patch-server.jar)" 1>&2
    exit 1
fi
if [[ -e logging.properties ]]
then
    LOGGING=-Djava.util.logging.config.file=logging.properties
fi

function usage() {
    echo "Commands: server, mk, rm, list, get, add, parse, path, r2p, " 1>&2
    ##echo "Class path: $DELTA_CP:${JENA_CP}"
    exit
}

if [[ $# = 0 ]]
then
    usage
    exit
else
    CMD="$1"
    shift
fi

# Map CMD to class name
BASE_PKG="org.seaborne.delta"
DCMD_PKG="${BASE_PKG}.cmds"

# Alternative names.
case $CMD in
    help|-h|--help)
	usage
	;;
    appendpatch|append|add)
	CMD=addpatch ;;
    mk)
	CMD=mklog ;;
    rm)
	CMD=rmlog ;;
    get)
	CMD=getpatch ;;
    r2p)
	CMD=rdf2patch ;;
    p2r)
	CMD=patch2rdf ;;
     parse|validate)
	CMD=patchparse ;;
    *) ;;
esac

# Map to class name.
case $CMD in
    "")
    ;;
    mklog | rmlog | list | addpatch | getpatch )
	CMD_CLS="$DCMD_PKG"."$CMD"
	;;
    ls)
        CMD_CLS="${DCMD_PKG}.list"
	;;
    rdf2patch | patch2rdf)
	CMD_CLS="$DCMD_PKG"."$CMD"
	;;
    patchserver | server )
	CMD_CLS="delta.server.DeltaServer"
	;;
    org.seaborne.delta.* | delta.* )
	CMD_CLS=$CMD
	;;
    tools.*)
	CMD_CLS="${BASE_PKG}"."$CMD"
	;;
    *)
	echo "Unknown command $CMD" 2>&1
	exit 1
    ;;

esac

java $JVM_ARGS $LOGGING -cp "$CP" "$CMD_CLS" "$@"
