/* Generated By:JavaCC: Do not edit this line. TIOjavaccConstants.java */
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.seaborne.riot.tio.alt.javacc ;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TIOjavaccConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int WS = 8;
  /** RegularExpression Id. */
  int WSC = 9;
  /** RegularExpression Id. */
  int BOM = 10;
  /** RegularExpression Id. */
  int IRI = 11;
  /** RegularExpression Id. */
  int PNAME_NS = 12;
  /** RegularExpression Id. */
  int PNAME_LN = 13;
  /** RegularExpression Id. */
  int BLANK_NODE_LABEL = 14;
  /** RegularExpression Id. */
  int VAR = 15;
  /** RegularExpression Id. */
  int LANGTAG = 16;
  /** RegularExpression Id. */
  int A2Z = 17;
  /** RegularExpression Id. */
  int A2ZN = 18;
  /** RegularExpression Id. */
  int DATATYPE = 19;
  /** RegularExpression Id. */
  int AT = 20;
  /** RegularExpression Id. */
  int TRUE = 21;
  /** RegularExpression Id. */
  int FALSE = 22;
  /** RegularExpression Id. */
  int ANY = 23;
  /** RegularExpression Id. */
  int KEYWORD = 24;
  /** RegularExpression Id. */
  int DOT = 25;
  /** RegularExpression Id. */
  int DIGITS = 26;
  /** RegularExpression Id. */
  int INTEGER = 27;
  /** RegularExpression Id. */
  int DECIMAL = 28;
  /** RegularExpression Id. */
  int EXPONENT = 29;
  /** RegularExpression Id. */
  int DOUBLE = 30;
  /** RegularExpression Id. */
  int INTEGER_POSITIVE = 31;
  /** RegularExpression Id. */
  int DECIMAL_POSITIVE = 32;
  /** RegularExpression Id. */
  int DOUBLE_POSITIVE = 33;
  /** RegularExpression Id. */
  int INTEGER_NEGATIVE = 34;
  /** RegularExpression Id. */
  int DECIMAL_NEGATIVE = 35;
  /** RegularExpression Id. */
  int DOUBLE_NEGATIVE = 36;
  /** RegularExpression Id. */
  int QUOTE_3D = 37;
  /** RegularExpression Id. */
  int QUOTE_3S = 38;
  /** RegularExpression Id. */
  int ECHAR = 39;
  /** RegularExpression Id. */
  int STRING_LITERAL1 = 40;
  /** RegularExpression Id. */
  int STRING_LITERAL2 = 41;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG1 = 42;
  /** RegularExpression Id. */
  int STRING_LITERAL_LONG2 = 43;
  /** RegularExpression Id. */
  int LPAREN = 44;
  /** RegularExpression Id. */
  int RPAREN = 45;
  /** RegularExpression Id. */
  int LBRACE = 46;
  /** RegularExpression Id. */
  int RBRACE = 47;
  /** RegularExpression Id. */
  int LBRACKET = 48;
  /** RegularExpression Id. */
  int RBRACKET = 49;
  /** RegularExpression Id. */
  int SEMICOLON = 50;
  /** RegularExpression Id. */
  int COLON = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int EQ = 53;
  /** RegularExpression Id. */
  int GT = 54;
  /** RegularExpression Id. */
  int LT = 55;
  /** RegularExpression Id. */
  int TILDE = 56;
  /** RegularExpression Id. */
  int PLUS = 57;
  /** RegularExpression Id. */
  int MINUS = 58;
  /** RegularExpression Id. */
  int UNDERSCORE = 59;
  /** RegularExpression Id. */
  int STAR = 60;
  /** RegularExpression Id. */
  int PN_CHARS_BASE = 61;
  /** RegularExpression Id. */
  int PN_CHARS_U = 62;
  /** RegularExpression Id. */
  int PN_CHARS = 63;
  /** RegularExpression Id. */
  int PN_PREFIX = 64;
  /** RegularExpression Id. */
  int PN_LOCAL = 65;
  /** RegularExpression Id. */
  int VAREXTRA = 66;
  /** RegularExpression Id. */
  int PN_CHARS_U2 = 67;
  /** RegularExpression Id. */
  int VARNAME = 68;
  /** RegularExpression Id. */
  int PN_LOCAL_ESC = 69;
  /** RegularExpression Id. */
  int PLX = 70;
  /** RegularExpression Id. */
  int HEX = 71;
  /** RegularExpression Id. */
  int PERCENT = 72;
  /** RegularExpression Id. */
  int HEX_INT = 73;
  /** RegularExpression Id. */
  int UNKNOWN = 74;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 7>",
    "<WS>",
    "<WSC>",
    "\"\\ufeff\"",
    "<IRI>",
    "<PNAME_NS>",
    "<PNAME_LN>",
    "<BLANK_NODE_LABEL>",
    "<VAR>",
    "<LANGTAG>",
    "<A2Z>",
    "<A2ZN>",
    "\"^^\"",
    "\"@\"",
    "\"true\"",
    "\"false\"",
    "\"any\"",
    "<KEYWORD>",
    "\".\"",
    "<DIGITS>",
    "<INTEGER>",
    "<DECIMAL>",
    "<EXPONENT>",
    "<DOUBLE>",
    "<INTEGER_POSITIVE>",
    "<DECIMAL_POSITIVE>",
    "<DOUBLE_POSITIVE>",
    "<INTEGER_NEGATIVE>",
    "<DECIMAL_NEGATIVE>",
    "<DOUBLE_NEGATIVE>",
    "\"\\\"\\\"\\\"\"",
    "\"\\\'\\\'\\\'\"",
    "<ECHAR>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<STRING_LITERAL_LONG1>",
    "<STRING_LITERAL_LONG2>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\":\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"~\"",
    "\"+\"",
    "\"-\"",
    "\"_\"",
    "\"*\"",
    "<PN_CHARS_BASE>",
    "<PN_CHARS_U>",
    "<PN_CHARS>",
    "<PN_PREFIX>",
    "<PN_LOCAL>",
    "<VAREXTRA>",
    "<PN_CHARS_U2>",
    "<VARNAME>",
    "<PN_LOCAL_ESC>",
    "<PLX>",
    "<HEX>",
    "<PERCENT>",
    "<HEX_INT>",
    "<UNKNOWN>",
  };

}
