/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    testImplementation("org.slf4j:slf4j-jdk14:1.7.30")
}

description = "RDF Patch"
