/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "rdf-delta"
include(":rdf-delta-integration-tests")
include(":rdf-delta-examples")
include(":rdf-patch")
include(":rdf-delta-client")
include(":rdf-delta-server-local")
include(":rdf-delta-server-extra")
include(":rdf-delta-base")
include(":rdf-delta-dist")
include(":rdf-delta-server")
include(":rdf-delta-fuseki")
include(":rdf-delta-server-http")
include(":rdf-delta-cmds")
include(":rdf-delta-fuseki-server")
