/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    jacoco
    id("org.seaborne.rdf-delta.java-conventions")
}

configurations {
    create("testJar")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation("org.rocksdb:rocksdbjni:6.20.3")
    implementation("org.apache.curator:curator-recipes:${project.property("ver.curator")}")
    implementation("org.apache.zookeeper:zookeeper") {
        version {
            strictly("3.7.0")
        }
    }
    testImplementation("org.apache.curator:curator-test:${project.property("ver.curator")}")
    testImplementation("org.slf4j:slf4j-jdk14:${project.property("ver.slf4j")}")
}

description = "RDF Delta :: Server (Local)"

tasks {
    register<Jar>("testJar") {
        archiveFileName.set("rdf-delta-server-local-test-${archiveVersion}.jar")
        from(project.the<SourceSetContainer>()["test"].output)
    }

    getByName("assemble").dependsOn("testJar")
}

artifacts {
    add("testJar", tasks.getByName("testJar"))
}

tasks.jacocoTestReport {
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
        html.isEnabled = false
    }
}
