/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.seaborne.rdf-delta.java-conventions")
}

configurations {
    create("testJar")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation("org.rocksdb:rocksdbjni:6.20.3")
    implementation("org.apache.curator:curator-recipes:5.1.0")
    testImplementation("org.apache.curator:curator-test:5.1.0")
    testImplementation("org.slf4j:slf4j-jdk14:1.7.30")
}

description = "RDF Delta :: Server (Local)"

tasks {
    register<Jar>("testJar") {
        archiveFileName.set("rdf-delta-server-local-test-$version.jar")
        from(project.the<SourceSetContainer>()["test"].output)
    }

    getByName("assemble").dependsOn("testJar")
}

artifacts {
    add("testJar", tasks.getByName("testJar"))
}
