#!/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

## Run a RDF Delta Patch Log Server
## This is the common script run from within directories zk1, zk2 and zk3.

ID=$(cat ZkData/myid)
CONNECT="localhost:2181,localhost:2182,localhost:2183"
PORT="107${ID}"

echo "Run Delta Patch Server : id = $ID : port = $PORT"

dcmd server --port "$PORT" --zk="$CONNECT" --zkCfg=./zoo.cfg
