/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-delta-base"))
    implementation(project(":rdf-patch"))
}

description = "RDF Delta :: Client"
