/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `jacoco`
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-patch"))
    testImplementation("org.slf4j:slf4j-jdk14:1.7.30")
}

description = "RDF Delta :: Base"
