/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.seaborne.patch.binary.thrift;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-08-10")
public enum Transaction implements org.apache.thrift.TEnum {
  TX(0),
  TC(1),
  TA(2),
  Segment(3);

  private final int value;

  private Transaction(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Transaction findByValue(int value) {
    switch (value) {
      case 0:
        return TX;
      case 1:
        return TC;
      case 2:
        return TA;
      case 3:
        return Segment;
      default:
        return null;
    }
  }
}
