#!/bin/bash
## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

if [ "$#" != 1 ]
then
    echo "Usage: $(basename $0) FILE" 2>&1
    exit 1
fi


# Find the namespace
PKG=../src/main/java/org/seaborne/patch/binary/thrift
rm -f "$PKG"/*.java

thrift -r -out ../src/main/java -gen java "$@"

# Also fixup Transaction.java for missing @Override.
for f in "$PKG"/*.java
do
    perl -i -p -e 's/\@SuppressWarnings.*/\@SuppressWarnings("all")/' $f
done
