/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation(project(":rdf-delta-server-local"))
    implementation(project(path = ":rdf-delta-server-local", configuration = "testJar"))
    implementation("com.amazonaws:aws-java-sdk-s3:1.11.908")
    implementation("javax.xml.bind:jaxb-api:2.3.1")
    implementation("org.slf4j:jcl-over-slf4j:1.7.30")
    testImplementation(project(":rdf-delta-server-local"))
    testImplementation("org.apache.curator:curator-test:5.1.0")
    testImplementation("io.findify:s3mock_2.12:0.2.6")
    testImplementation("org.slf4j:slf4j-jdk14:1.7.30")
}

description = "RDF Delta :: Server (Extra Components)"
