/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `jacoco`
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation(project(":rdf-delta-server-local"))
    implementation(project(":rdf-delta-server-http"))
    implementation(project(":rdf-delta-client"))
    implementation(project(":rdf-delta-fuseki"))
    implementation("org.apache.jena:jena-fuseki-main:3.17.0")
    implementation("org.apache.logging.log4j:log4j-slf4j-impl:2.14.1")
}

description = "RDF Delta :: Examples"

tasks.jacocoTestReport {
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
        html.isEnabled = false
    }
}
