/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `jacoco`
    id("org.seaborne.rdf-delta.java-conventions")
}

dependencies {
    implementation(project(":rdf-patch"))
    implementation(project(":rdf-delta-base"))
    implementation(project(":rdf-delta-server"))
    implementation(project(":rdf-delta-server-local"))
    implementation(project(path = ":rdf-delta-server-local", configuration = "testJar"))
    implementation(project(":rdf-delta-server-http"))
    implementation(project(":rdf-delta-client"))
    implementation("org.apache.jena:jena-fuseki-main:3.17.0")
    implementation("org.awaitility:awaitility:4.1.0")
    implementation("org.slf4j:slf4j-jdk14:1.7.30")
    implementation("org.apache.curator:curator-recipes:5.1.0")
    implementation("org.apache.curator:curator-test:5.1.0")
}

description = "RDF Delta :: Integration Tests"

tasks.jacocoTestReport {
    reports {
        xml.isEnabled = true
        csv.isEnabled = false
        html.isEnabled = false
    }
}
